# Generated by Django 5.0.2 on 2025-06-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_tour_number_of_adults_tour_number_of_children_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='number_of_adults',
            new_name='adults',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='number_of_children',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='number_of_kids',
            new_name='kids',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_participants',
        ),
    ]
