# Generated by Django 5.0.2 on 2025-06-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_destination_city'),
        ('schedule', '0003_rename_number_of_adults_tour_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='DestinationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kid_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='destination.destination')),
            ],
        ),
    ]
