# Generated by Django 5.0.2 on 2025-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('institutions', 'Institutions'), ('national_park', 'National Park'), ('camping', 'Camping'), ('rock_climbing', 'Rock Climbing')], max_length=100),
        ),
    ]
