# Generated by Django 5.0.2 on 2025-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('institutions', 'Institutions'), ('national_park', 'National Park'), ('camping', 'Camping'), ('rock_climbing', 'Rock Climbing')], max_length=100),
        ),
    ]
