# Generated by Django 5.0.2 on 2025-06-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_category_custom_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='custom_name',
            field=models.CharField(blank=True, help_text="Enter custom category name if 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('institutions', 'Institutions'), ('national_park', 'National Park'), ('camping', 'Camping'), ('rock_climbing', 'Rock Climbing'), ('other', 'Other')], max_length=100),
        ),
    ]
