# Generated by Django 5.0.2 on 2025-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_alter_category_custom_name_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default='Lahore', max_length=100),
        ),
    ]
